# Generated by Django 4.2.14 on 2024-12-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smalltube_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
    ]
