# Generated by Django 4.2.14 on 2024-12-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smalltube_api', '0003_alter_templatesemails_options_alter_videos_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verifico el correo?'),
        ),
    ]
