# Generated by Django 4.2.14 on 2024-12-05 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smalltube_api', '0005_remove_users_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Fecha de actualización')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Fecha de creación')),
                ('comment', models.TextField(blank=True, max_length=255, null=True, verbose_name='comentario')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que escribio el mensaje')),
                ('id_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smalltube_api.videos', verbose_name='Video en el que comento')),
            ],
        ),
    ]
