# Generated by Django 4.2.14 on 2024-12-07 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smalltube_api', '0011_alter_category_options_remove_videos_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smalltube_api.category')),
                ('id_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smalltube_api.videos')),
            ],
            options={
                'verbose_name': 'categoria de los videos',
                'verbose_name_plural': 'categorias de los videos',
            },
        ),
    ]
