# Generated by Django 4.2.14 on 2024-12-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smalltube_api', '0012_videoscategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoStatistics',
        ),
    ]
