services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: smalltube_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: django_user            
      MYSQL_PASSWORD: "1193200727"    
      MYSQL_ROOT_PASSWORD: "1193200727"
                    
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
    container_name: django_app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: smalltube_db
      DATABASE_USER: django_user
      DATABASE_PASSWORD: 1193200727
    volumes:  
      - .:/usr/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:

networks:
  default:
    driver: bridge